SELECT 
concat(
CONCAT("HMSET m:p:", oid), 
IFNULL(CONCAT(' productOid ', '"', oid,'"'), ''),
IFNULL(CONCAT(' name ', '"',NAME,'"'), ''),
IFNULL(CONCAT(' type ', '"',TYPE,'"'), ''),
IFNULL(CONCAT(' incomeCalcBasis ', '"',incomeCalcBasis,'"'), ''),
IFNULL(CONCAT(' raiseStartDateType ',  '"',raiseStartDateType,'"'), ''),
IFNULL(CONCAT(' raiseEndDate ', '"',raiseEndDate, '"'), ''),
IFNULL(CONCAT(' expAror ', '"',expAror,'"'), ''),
IFNULL(CONCAT(' expArorSec ', '"',expArorSec,'"'), ''),
IFNULL(CONCAT(' rewardInterest ', '"',rewardInterest,'"'), ''),
IFNULL(CONCAT(' netUnitShare ', '"', truncate(netUnitShare * 10000, 0), '"'), ''),
CONCAT(' investMin ', '"', truncate(IFNULL(investMin * 10000, 0), 0), '"'),
CONCAT(' investAdditional ', '"', truncate(IFNULL(investAdditional * 10000, 0), 0) ,'"'),
CONCAT(' investMax ', '"', truncate(IFNULL(investMax * 10000, 0), 0) , '"'), 
CONCAT(' minRredeem ', '"', truncate(IFNULL(minRredeem * 10000, 0), 0) , '"'),
CONCAT(' maxRredeem ', '"', truncate(IFNULL(maxRredeem * 10000, 0), 0) ,'"'),
CONCAT(' additionalRredeem ', '"', truncate(IFNULL(additionalRredeem * 10000, 0), 0),'"'),
CONCAT(' netMaxRredeemDay ', '"', truncate(IFNULL(netMaxRredeemDay*10000, 0), 0) ,'"'),
CONCAT(' dailyNetMaxRredeem ', '"', truncate(IFNULL(dailyNetMaxRredeem*10000, 0), 0) ,'"'),
IFNULL(CONCAT(' maxHold ', '"', truncate(IFNULL(maxHold * 10000, 0), 0),'"'), ''),
CONCAT(' singleDailyMaxRedeem ', '"', truncate(IFNULL(singleDailyMaxRedeem * 10000, 0), 0), '"'),
IFNULL(CONCAT(' setupDate ', '"', setupDate, '"'), ''),
IFNULL(CONCAT(' state ', '"',state,'"'), ''),
IFNULL(CONCAT(' raiseFailDate ', '"', raiseFailDate, '"'), ''),
IFNULL(CONCAT(' durationPeriodEndDate ', '"', durationPeriodEndDate, '"'), ''),
IFNULL(CONCAT(' currentVolume ', '"', truncate(IFNULL(currentVolume*10000, 0), 0), '"'), ''),
IFNULL(CONCAT(' collectedVolume ', '"', truncate(IFNULL(collectedVolume*10000, 0), 0),'"'), ''),
IFNULL(CONCAT(' maxSaleVolume ', '"', truncate(IFNULl(maxSaleVolume*10000, 0), 0), '"'), ''),
IFNULL(CONCAT(' lockCollectedVolume ', '"', truncate(IFNULL(lockCollectedVolume*10000, 0), 0), '"'), ''),
IFNULL(CONCAT(' repayDate ', '"', repayDate, '"'), ''),
IFNULL(CONCAT(' isOpenPurchase ', '"',isOpenPurchase ,'"'), ''),
IFNULL(CONCAT(' isOpenRemeed ', '"',isOpenRemeed,'"'), ''),
CONCAT(' dealStartTime ', '"', case when dealStartTime is null then '000000' when 0 = LENGTH(dealStartTime) then '000000' else dealStartTime end, '"'),
CONCAT(' dealEndTime ', '"', case when dealEndTime is null then '000000' when 0 = LENGTH(dealEndTime) then '000000' else dealEndTime end, '"'),
IFNULL(CONCAT(' previousCurVolume ', '"', truncate(IFNULL(previousCurVolume*10000, 0), 0),'"'), ''),
IFNULL(CONCAT(' previousCurVolumePercent ', '"', truncate(IFNULl(previousCurVolumePercent, 0), 0), '"'), ''),
IFNULL(CONCAT(' isPreviousCurVolume ', '"',isPreviousCurVolume,'"'), ''),
IFNULL(CONCAT(' singleDayRedeemCount ', '"',singleDayRedeemCount,'"'), '')
)
FROM t_gam_product
 WHERE oid in ('#oids') or '#xoids'='x';

