# 更新持仓还款计划表, 增加还款日字段
ALTER TABLE T_GAM_PORTFOLIO_ILLIQUID_HOLD_REPAYMENT ADD dueDate DATE;
# 更新预计还款计划表, 增加还款日字段
ALTER TABLE T_GAM_ILLIQUID_REPAYMENT_PLAN ADD dueDate DATE;
#修改净值校准表，nav字段长度
ALTER TABLE T_GAM_PORTFOLIO_NET_CORRECT MODIFY COLUMN nav DECIMAL(16,4);